baseurl = "http://lee2sman.github.io/intermediate-programming/"
# remember trailing / at end of baseurl
canonifyURLs = true
languageCode = "en-us"
title = "Intermediate Programming @Woodbury"
paginate = 50
theme = "sublime-hugo-theme"
publishDir = "docs"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Woodbury University"
	description = "Applied Computer Science"
	copyright = "CC4.0 BY"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "Bummer. The requested page was not <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Lee Tusman, Woodbury University"
	bio = "Applied Computer Science"
	bio2 = "Tech 1710"
	subscribe = "Subscribe"
	followme = "Contact"

	# Enable Google search
	search_enabled = true
	search = "Search"

[[params.offcanvas.socialnetworks]]
		name = "Instructor: Lee Tusman"
		url = "mailto:please_use_my_website@thank.you"
